language: erlang
otp_release:
  - 19.3
  - 20.3
install:
  - make
  - ./rebar3 update
script:
  - make test
  - make reltest
  - make systests
  - make dialyzer
  - make lint
notifications:
  email: bieniusa@cs.uni-kl.de
sudo: required
dist: trusty
